### ISSUE TITLE
Dog

### ISSUE THREAD

**Issue by SharkyOnGitHub** [dogix-os/dogix-website#1]
Dogs can get various types of cancer, including lymphoma, bone cancer, and breast cancer. Treatment options include surgery, radiation therapy, and chemotherapy. Some types of cancer are more treatable than others, so it's important to catch the illness early. Dog owners should be aware of the symptoms of cancer and consult their veterinarian if they notice anything out of the ordinary.

**Comment by jtbx** [comment]
Thanks for the feedback

**Comment by jtbx** [comment]
Thanks for the reminder. I'll merge a disclaimer.
